# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React CI/CD
# when push to ur repo on this specific branch, the whole workflows will get triggered
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#jobs you want to execute
jobs:
  build:
#can use ghaction on github server itself, dont have to use ur own virtual private server
#self-hosted cause we hosting this on our own server
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#npm ci clean install
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm test
    - run: npm run build 